/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JOptionPane;
import Interfaces.VentanaP;

/**
 *
 * @author IDEAPAD 330
 */
public class Login extends javax.swing.JFrame {


    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        textousuario.setText("admin");
        textoclave.setText("123");
    }
    void ocualtar(){
        if(opcion.getSelectedItem().equals("Gerente")){
            VentanaP v = new VentanaP();
            v.setVisible(true);
            v.setExtendedState(MAXIMIZED_BOTH);
        }else if(opcion.getSelectedItem().equals("Empleado")){
            
                VentanaP v = new VentanaP();
                
               v.Producto.setVisible(false);
               v.Empleado.setVisible(false);
               v.setVisible(true);
               v.setExtendedState(MAXIMIZED_BOTH);
                //v.Producto.setVisible(false);
            
        }
    }
    public void seleccionar(){ // sirve para que inicie el curso en le campo de texto 1
        textousuario.requestFocus();
        textousuario.selectAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        bnsalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textousuario = new javax.swing.JTextField();
        textoclave = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        opcion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bnsalir.setBackground(new java.awt.Color(102, 102, 102));
        bnsalir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bnsalir.setForeground(new java.awt.Color(255, 255, 255));
        bnsalir.setText("Salir");
        bnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(bnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 80, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Clave");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        textousuario.setBackground(new java.awt.Color(204, 204, 204));
        textousuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        getContentPane().add(textousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 170, 30));

        textoclave.setBackground(new java.awt.Color(204, 204, 204));
        textoclave.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        getContentPane().add(textoclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 170, 30));

        jButton1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 110, 40));

        opcion.setBackground(new java.awt.Color(204, 204, 204));
        opcion.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Empleado" }));
        getContentPane().add(opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 170, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lambor1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bnsalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     seleccionar();
     String Usuario = "admin";
     String Clave = "123";
     String Pass = new String(textoclave.getPassword());
     
     
     if(textousuario.getText().equals(Usuario) && Pass.equals(Clave)){
         
         
        VentanaP v = new VentanaP();
        ocualtar();
        
        // v.setExtendedState(MAXIMIZED_BOTH);// sirve para que la ventana principal se abra toda la pantalla
        // v.setVisible(true);
         dispose(); // sirve para que la ventana de acceso se cierre sola
         JOptionPane.showMessageDialog(null, "BIENVENIDO");
     }else{
         JOptionPane.showMessageDialog(null,"Uuario / Clave Incorrectas");
         
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnsalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JComboBox<String> opcion;
    private javax.swing.JPasswordField textoclave;
    private javax.swing.JTextField textousuario;
    // End of variables declaration//GEN-END:variables
}

