/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Empleado;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author IDEAPAD 330
 */
public class registroempleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form registroempleado
     */
    public registroempleado() {
        initComponents();
    }
    private void limpiar() {
        textotitulacion.setText("");
        textoapellido.setText("");
        textodni.setText("");
        textoedad.setText(" ");
        textocargo.setText(" ");
        textodireccion.setText("");
        textotelefono.setText("");
        textonombre.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textotitulacion = new javax.swing.JTextField();
        textoapellido = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textodireccion = new javax.swing.JTextField();
        textotelefono = new javax.swing.JTextField();
        registar = new javax.swing.JButton();
        textoedad = new javax.swing.JTextField();
        textocargo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textodni = new javax.swing.JTextField();
        textonombre = new javax.swing.JTextField();
        Fondo = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Registro de Empleados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Apellido");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Dirección");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Teléfono");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Titulación");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Edad");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Cargo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        textotitulacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textotitulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textotitulacionActionPerformed(evt);
            }
        });
        textotitulacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textotitulacionKeyTyped(evt);
            }
        });
        getContentPane().add(textotitulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 190, -1));

        textoapellido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textoapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoapellidoKeyTyped(evt);
            }
        });
        getContentPane().add(textoapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 190, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Nombre");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        textodireccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textodireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textodireccionKeyTyped(evt);
            }
        });
        getContentPane().add(textodireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 190, -1));

        textotelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textotelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textotelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(textotelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 190, -1));

        registar.setBackground(new java.awt.Color(255, 255, 255));
        registar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        registar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar24x24.png"))); // NOI18N
        registar.setText("Registar");
        registar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarActionPerformed(evt);
            }
        });
        getContentPane().add(registar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        textoedad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textoedad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoedadKeyTyped(evt);
            }
        });
        getContentPane().add(textoedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 190, -1));

        textocargo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textocargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textocargoKeyTyped(evt);
            }
        });
        getContentPane().add(textocargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 190, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Dni");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        textodni.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textodni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textodniKeyTyped(evt);
            }
        });
        getContentPane().add(textodni, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 190, -1));

        textonombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textonombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textonombreActionPerformed(evt);
            }
        });
        textonombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textonombreKeyTyped(evt);
            }
        });
        getContentPane().add(textonombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 190, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo degra.jpeg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 790, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textotitulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textotitulacionActionPerformed

    }//GEN-LAST:event_textotitulacionActionPerformed

    private void textotitulacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textotitulacionKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Digite solo letras");

        } else if (textotitulacion.getText().length() >= 30) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_textotitulacionKeyTyped

    private void textoapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoapellidoKeyTyped
        char validar = evt.getKeyChar();// sirve para validar que solo ingrese letras
        if (Character.isDigit(validar)) { // para validar que solo ingrese lettras
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Digite solo letras");
        } else if (textoapellido.getText().length() >= 25) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();// sirve para hacer un sonido al final
        }
    }//GEN-LAST:event_textoapellidoKeyTyped

    private void textodireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textodireccionKeyTyped

    }//GEN-LAST:event_textodireccionKeyTyped

    private void textotelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textotelefonoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo digite numeros");
        } else if (textotelefono.getText().length() >= 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_textotelefonoKeyTyped

    private void registarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarActionPerformed
        Coneccion co;
        PreparedStatement ps;
        Empleado c = new Empleado(textonombre.getText(), textoapellido.getText(),textodni.getText(),textoedad.getText()
            ,textocargo.getText(),textodireccion.getText(),textotelefono.getText(), textonombre.getText());

        // sirve para que el usuario llene todos los comapos
        if (textotitulacion.getText().equals(" ") || textoapellido.getText().equals(" ") ||textodni.getText().equals(" ")|| textoedad.getText().equals(" ")||textocargo.getText().equals(" ")
            ||textodireccion.getText().equals("")|| textotelefono.getText().equals(" ") || textotitulacion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
            // javax.swing.JOptionPane.showMessageDialog(this, "Llene todos los campos " + javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            co = new Coneccion();
            Connection con = co.getConexion();
            try {
                ps = (PreparedStatement) con.prepareStatement("insert into empleado(Nombre,Apellido,Dni,Edad,Cargo,Direccion,Telefono,Titulacion) values(?,?,?,?,?,?,?,?)");
                ps.setString(1, textonombre.getText());
                ps.setString(2, textoapellido.getText());
                ps.setString(3, textodni.getText());
                ps.setString(4, textoedad.getText());
                ps.setString(5, textocargo.getText());
                ps.setString(6, textodireccion.getText());
                ps.setString(7, textotelefono.getText());
                ps.setString(8, textotitulacion.getText());

                int res = ps.executeUpdate();

                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "Empleado guardado con Éxito !!!!!!!!!");
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "error");
                }
                con.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_registarActionPerformed

    private void textoedadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoedadKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo digite números");
        } else if (textoedad.getText().length() >= 2) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_textoedadKeyTyped

    private void textocargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textocargoKeyTyped
        char validar = evt.getKeyChar();// sirve para validar que solo ingrese letras
        if (Character.isDigit(validar)) { // para validar que solo ingrese lettras
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Digite solo letras");
        } else if (textocargo.getText().length() >= 20) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();// sirve para hacer un sonido al final
        }
    }//GEN-LAST:event_textocargoKeyTyped

    private void textodniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textodniKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo digite números");
        } else if (textodni.getText().length() >= 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_textodniKeyTyped

    private void textonombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textonombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textonombreActionPerformed

    private void textonombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textonombreKeyTyped
        char validar = evt.getKeyChar();// sirve para validar que solo ingrese letras
        if (Character.isDigit(validar)) { // para validar que solo ingrese lettras
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Digite solo letras");
        } else if (textonombre.getText().length() >= 25) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();// sirve para hacer un sonido al final
        }
    }//GEN-LAST:event_textonombreKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton registar;
    private javax.swing.JTextField textoapellido;
    private javax.swing.JTextField textocargo;
    private javax.swing.JTextField textodireccion;
    private javax.swing.JTextField textodni;
    private javax.swing.JTextField textoedad;
    private javax.swing.JTextField textonombre;
    private javax.swing.JTextField textotelefono;
    private javax.swing.JTextField textotitulacion;
    // End of variables declaration//GEN-END:variables
}
